<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-J9VQ03L" name="tutorialsTestNG.ExceptiontimeOut" tests="2" failures="0" timestamp="03 Sep 2019 23:16:22 GMT" time="0.252" errors="1">
  <testcase name="test1" time="0.005" classname="tutorialsTestNG.ExceptiontimeOut"/>
  <testcase name="infiniteloop" time="0.247" classname="tutorialsTestNG.ExceptiontimeOut">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method tutorialsTestNG.ExceptiontimeOut.infiniteloop() didn&#039;t finish within the time-out 200">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method tutorialsTestNG.ExceptiontimeOut.infiniteloop() didn't finish within the time-out 200
at tutorialsTestNG.ExceptiontimeOut.infiniteloop(ExceptiontimeOut.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- infiniteloop -->
</testsuite> <!-- tutorialsTestNG.ExceptiontimeOut -->
